
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./ssl:/etc/nginx/ssl:ro 
      - ./logs/nginx:/var/log/nginx  
    depends_on:
      - backend
    restart: always
    environment:
      - VITE_API_URL=https://freelance-marketplace.my/api

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    expose:
      - "5000"
    volumes:
      - ./backend/uploads:/app/uploads
      - ./logs/backend:/app/logs
    restart: always
    env_file:
      - .env 
    environment:
      - MONGODB_URI=${MONGODB_URI}

volumes:
  uploads:
  logs:

networks:
  default:
    driver: bridge